### ISSUE TITLE
Feature: User can interact with game in a 1x1 square by clicking it and inputting a guess

### ISSUE THREAD

**Issue by Ajowyang** [Ajowyang/yugioh-grid#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List
- [x] Create HTML layout
   - [x] create a row for header at the top with logo
   - [x] create container div for the entire game including the grid, categories, buttons, and game mode change elements
     - [x] create row div containing grid size changer
     - [x] create row div containing grid including categories
       - [x] create row div containing category changer and div of categories at top 
         - [x] create div with category changer 
         - [x] create row div with class 'col-categories' of top categories, create first one: div with class 'col-category'
       - [x] create row div containing col div which contains left side categories and the grid
         - [x] create col div with class 'row-categories' of left side categories, create first one : div with class 'row-category'
         - [x] create col div of grid square rows, create first row with one div for first square with class 'grid-sq row1 col1'
         - [x] create img element inside grid square(s)
   - [x] create form with modal with input field and submit button that is hidden
- [x] Ensure the display looks nice on Mobile and Desktop
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] add event hover functionality to highlight grid square(s) 
- [x] create arrays populated with objects that correspond to top and left categories
  - [x] topCategories = [{'checkFor': '___', 'val: '___'}, {'checkFor': '___', 'val': '___}, {'checkFor': '___', 'val': '___'}]
  - [x] leftCategories = [{'checkFor': '___', 'val': '___'}, {'checkFor': '___', 'val': '___}, {'checkFor': '___', 'val': '___'}]
- [x] add click event handler to grid square(s) to show modal
- [x] add submit handler to modal
  - [x] fetch response with string from user input
  - [x] get checkFor and val values of top and left category attribute, check if response[checkFor] = val for both categories
  - [x] if response is correct, set img src attribute to reponse's image URL, change grid square color to green
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.  

> ##### Commit checklist for tasks needed to complete the feature.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
