### ISSUE TITLE
Feature: User can view their accuracy stats

### ISSUE THREAD

**Issue by Ajowyang** [Ajowyang/yugioh-grid#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List
- [x] create modal window that shows #guesses, #correct, and percentage correct
  - [x] create header that says 'Stats'
  - [x] add an 'x' font awesome icon on the top right corner to close the window
  - [x] add a row div that contains 3 boxes that show guesses, correct, and accuracy percentage respectively
  - [x] add 3 column divs that are the boxes with the heading on top and text content below
- [x] add submit event handler to the modal window that will close on click of the x icon at top right or click away from the main content
- [x] Create function to calculate and set the correct text values of each box to be called each time a user makes a guess
- [x] Implement this function into existing code to add stat calculating functionality
- [x] Make modal window pop up when user completes grid

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
