### ISSUE TITLE
Feature: User can can clear the grid to play again

### ISSUE THREAD

**Issue by Ajowyang** [Ajowyang/yugioh-grid#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] query a nodeList of the gamesquare divs
- [x] Create function to clear squares 
  - [x] get list of all game squares and iterate through them
  - [x] delete image container, image, reset background color back to white and hover highlight functionality
  - [x] reset stats modal text and numCorrect, guesses, completedSquares variables back to 0
- [x] query the 'CLEAR GRID' button
- [x] Add event lister that will call the function we made on click for the CLEAR GRID button

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
