### ISSUE TITLE
Feature: User can switch grid category sets

### ISSUE THREAD

**Issue by Ajowyang** [Ajowyang/yugioh-grid#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] creates function that changes grid categories
  - [x] must clear existing categories, sets grid ID text label to new grid ID#, renders new categories, clears existing stat variables
- [x] create modal for user that contains list of grid category sets by ID for user to select
  - [x] create a column div
  - [x] first row is the heading with text 'GRIDS'
  - [x] following is a container that holds rows are row divs with image in container and text saying Grid #? holding ids that correspond to their keys in the grid category object
- [x] render the modal with rows for each set of categories in the grid category sets object
- [x] create click event handler on those rows that calls function to render new grid categories

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
